// Expo config plugin: inject a release signingConfig into android/app/build.gradle
// during `expo prebuild`.
//
// Why a plugin instead of editing android/app/build.gradle directly?
//   android/ is gitignored — it is regenerated by `expo prebuild`, so any manual
//   edit there is wiped on the next prebuild. Expressing the signing config as a
//   plugin makes a *signed* build reproducible from source and keeps the repo
//   merge-clean (we never touch upstream files).
//
// Credentials live in mobile/credentials/keystore.properties (gitignored). When
// that file is absent (CI, a contributor without the keystore) the release
// buildType falls back to the debug key so `expo prebuild` + a debug build still
// work — only the signed release APK needs the real keystore.
//
// keystore.properties format (paths relative to the mobile/ root):
//   storeFile=credentials/release.keystore
//   storePassword=...
//   keyAlias=freellmapiphone-release
//   keyPassword=...

const { withAppBuildGradle } = require('@expo/config-plugins');

const RELEASE_SIGNING_CONFIG = `
        release {
            def ksPropsFile = rootProject.file('../credentials/keystore.properties')
            if (ksPropsFile.exists()) {
                def ksProps = new Properties()
                ksProps.load(new FileInputStream(ksPropsFile))
                storeFile rootProject.file('../' + ksProps['storeFile'])
                storePassword ksProps['storePassword']
                keyAlias ksProps['keyAlias']
                keyPassword ksProps['keyPassword']
            }
        }`;

// The release buildType in the default RN template, uniquely marked by its
// "Caution!" comment (the debug buildType has no such comment), so this never
// matches the debug signingConfig.
const RELEASE_BUILDTYPE_RE =
  /(release \{\s*\/\/ Caution![\s\S]*?signed-apk-android\.\s*)signingConfig signingConfigs\.debug/;

function addReleaseSigningConfig(gradle) {
  if (gradle.includes("rootProject.file('../credentials/keystore.properties')")) {
    return gradle; // already applied — idempotent across repeated prebuilds
  }

  // 1. Define signingConfigs.release inside the existing signingConfigs { } block.
  if (!gradle.includes('signingConfigs {')) {
    throw new Error('withReleaseSigning: could not find signingConfigs block in build.gradle');
  }
  gradle = gradle.replace('signingConfigs {', `signingConfigs {${RELEASE_SIGNING_CONFIG}`);

  // 2. Point the release buildType at signingConfigs.release when the keystore
  //    exists, else keep the debug key so credential-less builds still succeed.
  if (!RELEASE_BUILDTYPE_RE.test(gradle)) {
    throw new Error('withReleaseSigning: could not find the release buildType signingConfig to replace');
  }
  gradle = gradle.replace(
    RELEASE_BUILDTYPE_RE,
    "$1signingConfig rootProject.file('../credentials/keystore.properties').exists() ? signingConfigs.release : signingConfigs.debug"
  );

  return gradle;
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning: expected android/app/build.gradle to be Groovy');
    }
    cfg.modResults.contents = addReleaseSigningConfig(cfg.modResults.contents);
    return cfg;
  });
};
