// SecretStore implementation backed by expo-secure-store (Android Keystore).
//
// Why a SYNCHRONOUS API:
//   The reused upstream router/health/embeddings code calls crypto-shim.decrypt()
//   synchronously while building a request (see server/src/services/router.ts:649).
//   crypto-shim resolves the secret by calling SecretStore.get(ref), so get() — and
//   for symmetry put()/delete() — must be synchronous too. expo-secure-store exposes
//   matching synchronous methods, so no async refactor of upstream code is needed.
//
// Method names (expo-secure-store ~14.0.0 / Expo SDK 53):
//   - SecureStore.setItem(key, value, options)        -> sync, void
//   - SecureStore.getItem(key, options)               -> sync, string | null
//   - SecureStore.deleteItemAsync(key, options)       -> async, Promise<void>
//   (setItemAsync/getItemAsync also exist; we use the sync variants where they
//    exist to preserve the upstream synchronous contract. There is NO sync
//    delete in expo-secure-store 14, so delete() fires deleteItemAsync without
//    awaiting — eviction is best-effort cleanup, no caller needs its result.)
//
// Storage characteristics on Android:
//   - Values are stored in SharedPreferences, encrypted with a key held in the
//     hardware-backed Android Keystore. Plaintext secrets never hit disk.
//   - Android caps a stored VALUE at ~2048 bytes. API keys (tens of chars) are far
//     under this, but we guard put() so an oversized secret fails loudly here rather
//     than with an opaque native error.
//   - Keys (the `ref` argument) must match [A-Za-z0-9._-]; our refs are generated by
//     crypto-shim from that alphabet, so they are always valid.

import * as SecureStore from 'expo-secure-store';
import type { SecretStore } from '../contracts';

// Android Keystore value size limit. Keep a small margin below the documented
// ~2048-byte ceiling to stay clear of platform encoding overhead.
const MAX_VALUE_BYTES = 2048;

function byteLength(value: string): number {
  // RN/Hermes lacks Buffer by default; count UTF-8 bytes via TextEncoder when
  // available, else fall back to a manual code-point pass.
  if (typeof TextEncoder !== 'undefined') {
    return new TextEncoder().encode(value).length;
  }
  let bytes = 0;
  for (let i = 0; i < value.length; i++) {
    const c = value.charCodeAt(i);
    if (c < 0x80) bytes += 1;
    else if (c < 0x800) bytes += 2;
    else if (c >= 0xd800 && c <= 0xdbff) {
      bytes += 4; // surrogate pair -> 4 bytes, skip the low surrogate
      i++;
    } else bytes += 3;
  }
  return bytes;
}

export const secretStore: SecretStore = {
  put(ref: string, secret: string): void {
    const size = byteLength(secret);
    if (size > MAX_VALUE_BYTES) {
      throw new Error(
        `SecretStore.put: secret for ref "${ref}" is ${size} bytes, exceeds the ` +
          `Android Keystore limit of ${MAX_VALUE_BYTES} bytes.`,
      );
    }
    SecureStore.setItem(ref, secret);
  },

  get(ref: string): string | null {
    return SecureStore.getItem(ref);
  },

  delete(ref: string): void {
    // expo-secure-store has no synchronous delete; fire-and-forget the async
    // one. Failure to evict is non-fatal (the ref is already unreachable once
    // its api_keys row is gone) but logged so it isn't silent.
    SecureStore.deleteItemAsync(ref).catch((err: unknown) => {
      console.warn(`SecretStore.delete: failed to evict ref "${ref}":`, err);
    });
  },
};

export default secretStore;
